const endPointsConstants = {
REPORT__CREATE_REPORT : 'REPORT__CREATE_REPORT',
REPORT__GET_REPORTS_BY_ID:'REPORT__GET_REPORTS_BY_ID',
REPORT__GET_ALL_REPORTS:'REPORT__GET_ALL_REPORTS',
REPORT__UPDATE_REPORT:'REPORT__UPDATE_REPORT',
REPORT__DELETE_REPORT:'REPORT__DELETE_REPORT',
REPORT__GET_DEPARTMENT_ANALYTICS:'REPORT__GET_DEPARTMENT_ANALYTICS',
REPORT__GET_REPORTERS_ANALYTICS:'REPORT__GET_REPORTERS_ANALYTICS',
REPORT__GET_REPORTS_DAILY_ANALYTICS:'REPORT__GET_REPORTS_DAILY_ANALYTICS',
REPORT__MONTHLY_EMAIL:'REPORT__MONTHLY_EMAIL',
REPORT__EXPORT_ALL_REPORTS:'REPORT__EXPORT_ALL_REPORTS',
REPORT__GET_THIS_YEAR_USER_REPORTS_COUNT: 'REPORT__GET_THIS_YEAR_USER_REPORTS_COUNT'
}

const ReportScale = ['day','week','month','year']

module.exports = {
    endPointsConstants,
    ReportScale
}
