const endPointsConstants = {
DEPARTMENT__CREATE_DEPARTMENT : 'DEPARTMENT__CREATE_DEPARTMENT',
DEPARTMENT__GET_ALL_DEPARTMENTS_NAMES: 'DEPARTMENT__GET_ALL_DEPARTMENTS_NAMES',
DEPARTMENT__GET_ALL_DEPARTMENTS:'DEPARTMENT__GET_ALL_DEPARTMENTS',
DEPARTMENT__UPDATE_DEPARTMENT:'DEPARTMENT__UPDATE_DEPARTMENT',
DEPARTMENT__DELETE_DEPARTMENT:'DEPARTMENT__DELETE_DEPARTMENT',
}


module.exports = {
    endPointsConstants
}