const endPointsConstants = {
AREA__CREATE_AREA : 'AREA__CREATE_AREA',
AREA__GET_ALL_AREAS_NAMES: 'AREA__GET_ALL_AREAS_NAMES',
AREA__GET_ALL_AREAS:'AREA__GET_ALL_AREAS',
AREA__UPDATE_AREA:'AREA__UPDATE_AREA',
AREA__DELETE_AREA:'AREA__DELETE_AREA',
}


module.exports = {
    endPointsConstants
}