const endPointsConstants = {
USER_LOGIN : 'USER_LOGIN',
USER_REGISTER:'USER_REGISTER',
USER_GET_USERS: 'USER_GET_USERS',
USER_UPDATE_USER:'USER_UPDATE_USER',
USER_GET_USER_BY_ID:'USER_GET_USER_BY_ID',
USER_DELETE_USER: 'USER_DELETE_USER',
USER_GET_USER_INFO:'USER_GET_USER_INFO',
USER_CHANGE_PASSWORD:'USER_CHANGE_PASSWORD',
}

const numberOfSecondsPerHour = 60*60 ;
module.exports = {
    endPointsConstants,
    numberOfSecondsPerHour
}